import turtle

t = turtle.Turtle()
t2 = turtle.Turtle()
t3 = turtle.Turtle()
screen = turtle.Screen()

screen.screensize(200,200,)
screen.bgcolor("peru")
turtle.addshape("intro.gif")
turtle.addshape("aboutme.gif")
t2.penup()
t2.shape("intro.gif")
t2.goto(0,0)
t2.stamp()
t2.shape("aboutme.gif")
t2.goto(-100,125)
t2.stamp
t.penup()
t.goto(0,150)
t.penup()
t.write("INTRO", font=("Times New Roman", 24, "bold"), align="center")
t.penup()
t.goto(0,125)
t.write("Kusal Timsina", font=("Times New Roman", 12, "bold"), align= "center")
t.goto(0,100)
t.write("This is the intro page. Press enter to move on", font=("Times New Roman", 12), align = "center")
t.goto(-100,0)
t.fillcolor("red")
t.begin_fill()
t.pendown()
t.circle(30)
t.end_fill()
t.penup()
enter = input("Press enter to flip the page")



t.clear()
t2.clearstamps()
t3.clear()
screen.bgcolor("orange")
t.goto(0,175)
t.write("Favorite Foods", font=("Times New Roman", 24, "bold"), align = "center")
turtle.addshape("french.gif")
turtle.addshape("yogurt.gif")
turtle.addshape("grapefruit.gif")
t2.penup()
t2.goto(-200,150)
t2.shape("french.gif")
t2.stamp()
t.goto(-200,75)
t.write("French Fries", font=("Times New Roman", 12, "bold"), align= "center")
t2.shape("yogurt.gif")
t2.goto(200,150)
t2.stamp()
t.goto(200,75)
t.write("Yogurt", font=("Times New Roman", 12, "bold"), align= "center")
t2.shape("grapefruit.gif")
t2.goto(0,-100)

t.goto(0,-175)
t.write("Grapefruit", font=("Times New Roman", 12, "bold"), align= "center")
t3.fillcolor("blue")
t3.penup()
t3.goto(-200,200)
t3.pendown()
t3.begin_fill()
t3.forward(100)
t3.left(90)
t3.forward(100)
t3.left(90)
t3.forward(100)
t3.left(90)
t3.forward(100)
t3.end_fill()
t3.penup()




enter = input("Press enter to flip the page")
t.clear()
t2.clear()
t2.clearstamps()
t3.clear()
screen.bgcolor("yellow")
t.goto(0,175)
t.write("Hobbies", font=("Times New Roman", 24, "bold"), align = "center")
turtle.addshape("minecraft.gif")
turtle.addshape("roblox.gif")
turtle.addshape("volleyball.gif")
turtle.addshape("artist.gif")

t2.shape("artist.gif")
t2.goto(0,-100)
t2.stamp()
t.goto(0,-175)
t.write("Drawing/doodling", font=("Times New Roman", 12, "bold"), align= "center")
t2.goto(150,50)
t2.shape("roblox.gif")
t2.stamp()
t.goto(150,-25)
t.write("Playing Roblox", font=("Times New Roman", 12, "bold"), align= "center")
t2.shape("minecraft.gif")
t2.goto(200,175)
t2.stamp()
t.goto(200,100)
t.write("playing Minecraft", font=("Times New Roman", 12, "bold"), align= "center")
t2.shape("volleyball.gif")
t2.goto(-200,-100)
t2.stamp()
t.goto(-200,-175)
t.write("playing volleyball", font=("Times New Roman", 12, "bold"), align= "center")

t3.goto(0,0)
t3.fillcolor("orange")
t3.pendown()
t3.begin_fill()
t3.setheading(0)
t3.left(45)
t3.forward(100)
t3.setheading(-45)
t3.forward(100)
t3.setheading(0)
t3.left(180)
t3.forward(150)
t3.end_fill()
t3.penup()

enter = input("Press enter to flip the page")
t.clear()
t2.clearstamps()
t3.clear()
screen.bgcolor("light green")
t.goto(0,175)
t.write("Favorite Movie", font=("Times New Roman", 24, "bold"), align = "center")
turtle.addshape("avengers.gif")
turtle.addshape("avengers2.gif")
t2.shape("avengers.gif")
t2.goto(0,0)
t2.stamp()
t.goto(0,-125)
t.write("Avengers Endgame", font=("Times New Roman", 12, "bold"), align= "center")
t2.shape("avengers2.gif")
t2.goto(100,100)
t2.stamp()

t.fillcolor("green")
t.goto(-5,100)
t.pendown()
t.begin_fill()
t.forward(150)
t.right(90)
t.forward(100)
t.right(90)
t.forward(150)
t.right(90)
t.forward(100)
t.right(90)
t.end_fill()



enter = input("Press enter to flip the page")
t.clear()
t3.clear()

t.penup()
t3.penup()
t2.penup()

t2.clearstamps()
screen.bgcolor("light blue")
t.goto(0,175)
t.write("Favorite Sport", font=("Times New Roman", 24, "bold"), align = "center")
turtle.addshape("badminton.gif")
turtle.addshape("bad2.gif")
t2.goto(-100,150)
t2.shape("badminton.gif")
t2.stamp()
t.goto(-120,50)
t.write("Badminton", font=("Times New Roman", 24, "bold"), align = "center")
t.goto(0,0)
t2.shape("bad2.gif")
t2.goto(175,120)
t2.stamp()
t.write("Enter to finish", font=("Times New Roman", 24, "bold"), align = "center")



t.fillcolor("cornsilk")
t.goto(55,50)
t.pendown()
t.begin_fill()
t.pendown()
t.right(45)
t.forward(75)
t.left(90)
t.forward(75)
t.left(90)
t.forward(75)
t.left(90)
t.forward(75)
t.end_fill()
t.penup()








turtle.done()








